#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi
mysql_root_password="$1"
backup_date=$(date +'%d-%m-%Y')
mysql_dump_file="backup.sql"
archive_file="$backup_date.tar.gz"
echo "Creating MySQL dump..."
mysqldump -u root --password="$mysql_root_password" --all-databases > "$mysql_dump_file"
echo "Creating compressed archive..."
tar -czvf "$archive_file" "$mysql_dump_file"
echo "Backup completed. Archive saved as $archive_file"
