#!/usr/bin/env bash
# configure nginx to listen on port 88
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-enabled/default
sudo service nginx restart
