#!/usr/bin/env bash
# This script displays Best School School 10 times using until loop but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	i=$((i+1))
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
done