#!/usr/bin/env bash
# This script diplays numbers from 1 to 20 and displays 4 and then bad luck from China for the 4th iteration, 9 and then bad luck from Japan for the 9th iteration, and 17 and then bad luck from Italy for the 17th iteration using while loop
i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	i=$((i+1))
done