#!/usr/bin/env bash
# This script displays the content of the current directory in a list format where only the part of the name after the first dash is displayed
list="$(ls)"
for i in $list
do
	echo "$i" | cut -d '-' -f 2
done