#!/usr/bin/env bash
#This script is fixing a container so that Nginx is running as the nginx user.
apt update
apt install -y nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;listen 8080 default_server;/g' /etc/nginx/sites-available/default
pkill apache2
service nginx restart
