#!/usr/bin/env bash
#This script is fixing a container so that Nginx is running as the nginx user.
chmod u=rw,go=r /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
su nginx -s /bin/bash -c "service nginx restart"
